[theme]
primaryColor = "#2980b9"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#2c3e50"
font = "sans serif"

[server]
port = 5000
headless = false
enableCORS = true
enableXsrfProtection = true